---
- name: install docker
  become: yes
  hosts: all
  tasks:
  - name: apt update
    shell: apt update

  - name: install requirements
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      state: present

  - name: curl
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: add-rep
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

  - name: apt update
    shell: apt update

  - name: apt cache-policy
    shell: apt-cache policy docker-ce

  - name: install docker
    apt: name=docker-ce state=present

  - name: enable docker
    shell: systemctl enable --now docker

  - name: cp
    copy: src=./web dest=/opt mode=0777

  - name: docker image web-53
    shell: cd /opt/web && docker build . -t web-53

  - name: docker_run_web-53
    shell: docker run --restart=always -p 8080:8080 -d --name web-53 --network=bridge web-53

  - name: docker_redis
    shell: docker run -d --name redis -p 6379:6379 --network=bridge --restart=always redis

  - name: docker_tra
    shell: docker run --name traefik --network=bridge --restart=always -p 5000:8080 -p 80:80 -d -p 443:443 --mount type=bind,source=/opt/web/traefik.yml,target=/etc/traefik/traefik.yml --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock --mount type=bind,source=/opt/web/dynamic_conf.yml,target=/etc/traefik/dynamic_conf.yml --mount type=bind,source=/opt/web/supercert.pem,target=/etc/traefik/supercert.pem --mount type=bind,source=/opt/web/supercert.key,target=/etc/traefik/supercert.key traefik:v2.4
